# frozen_string_literal: true

require_relative '../rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/appointments', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Appointment. As you add validations to Appointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    customer = create(:customer)
    stylist = create(:stylist)
    attributes_for(:appointment, customer_id: customer.id, stylist_id: stylist.id)
  end

  let(:invalid_attributes) do
    attributes_for(:invalid_appointment)
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # AppointmentsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    { 'CONTENT_TYPE' => 'application/json' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Appointment.create! valid_attributes
      get api_v1_appointments_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      appointment = Appointment.create! valid_attributes
      get api_v1_appointment_url(appointment), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Appointment' do
        expect do
          post api_v1_appointments_url,
               params: { appointment: valid_attributes },
               headers: valid_headers, as: :json
        end.to change(Appointment, :count).by(1)
      end

      it 'renders a JSON response with the new appointment' do
        post api_v1_appointments_url,
             params: { appointment: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Appointment' do
        expect do
          post api_v1_appointments_url,
               params: { appointment: invalid_attributes }, as: :json
        end.to change(Appointment, :count).by(0)
      end

      it 'renders a JSON response with errors for the new appointment' do
        post api_v1_appointments_url,
             params: { appointment: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        customer = create(:update_customer)
        stylist = create(:update_stylist)
        attributes_for(:update_appointment, customer_id: customer.id, stylist_id: stylist.id)
      end

      it 'updates the requested appointment' do
        appointment = Appointment.create! valid_attributes
        patch api_v1_appointment_url(appointment),
              params: { appointment: new_attributes }, headers: valid_headers, as: :json
        appointment.reload
        expect(appointment.customer_id).to eq new_attributes[:customer_id]
        expect(appointment.stylist_id).to eq new_attributes[:stylist_id]
        expect(appointment.appointment_on).to eq Appointment.order(:updated_at).last.appointment_on
        expect(appointment.remark).to eq new_attributes[:remark]
      end

      it 'renders a JSON response with the appointment' do
        appointment = Appointment.create! valid_attributes
        patch api_v1_appointment_url(appointment),
              params: { appointment: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the appointment' do
        appointment = Appointment.create! valid_attributes
        patch api_v1_appointment_url(appointment),
              params: { appointment: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested appointment' do
      appointment = Appointment.create! valid_attributes
      expect do
        delete api_v1_appointment_url(appointment), headers: valid_headers, as: :json
      end.to change(Appointment, :count).by(-1)
    end
  end
end
