require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Customer. As you add validations to Customer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:customer).attributes
  }

  let(:invalid_attributes) {
    build(:invalid_customer).attributes
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CustomersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {"ACCEPT" => "application/json"}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Customer.create! valid_attributes
      get api_v1_customers_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      customer = Customer.create! valid_attributes
      get api_v1_customer_url(customer), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Customer" do
        expect {
          post api_v1_customers_url,
               params: { customer: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Customer, :count).by(1)
      end

      it "renders a JSON response with the new customer" do
        post api_v1_customers_url,
             params: { customer: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Customer" do
        expect {
          post api_v1_customers_url,
               params: { customer: invalid_attributes }, as: :json
        }.to change(Customer, :count).by(0)
      end

      shared_examples 'check_status_and_content_type' do
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include("application/json")
      end

      it "renders a JSON response with errors for the new customer" do
        post api_v1_customers_url,
             params: { customer: invalid_attributes }, headers: valid_headers, as: :json
        it_behaves_like 'check_status_and_content_type'
      end

      it "名前が空白なら失敗する" do
        post api_v1_customers_url,
            params: { customer: build(:invalid_customers, :name_not_null).attributes },
            headers: valid_headers, as: :json
        it_behaves_like 'check_status_and_content_type'
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        build(:update_customer).attributes
      }

      it "updates the requested customer" do
        customer = Customer.create! valid_attributes
        patch api_v1_customer_url(customer),
              params: { customer: new_attributes }, headers: valid_headers, as: :json
        customer.reload
        expect(customer.name).to eq new_attributes['name']
        expect(customer.tel).to  eq new_attributes['tel']
        expect(customer.mail).to  eq new_attributes['mail']
      end

      it "renders a JSON response with the customer" do
        customer = Customer.create! valid_attributes
        patch api_v1_customer_url(customer),
              params: { customer: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the customer" do
        customer = Customer.create! valid_attributes
        patch api_v1_customer_url(customer),
              params: { customer: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested customer" do
      customer = Customer.create! valid_attributes
      expect {
        delete api_v1_customer_url(customer), headers: valid_headers, as: :json
      }.to change(Customer, :count).by(-1)
    end
  end
end
