# frozen_string_literal: true

require_relative '../rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/menus', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Menu. As you add validations to Menu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:menu)
  end

  let(:invalid_attributes) do
    attributes_for(:invalid_menu)
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MenusController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    { ACCEPT: 'application/json' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Menu.create! valid_attributes
      get api_v1_menus_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      menu = Menu.create! valid_attributes
      get api_v1_menu_url(menu), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Menu' do
        expect do
          post api_v1_menus_url,
               params: { menu: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Menu, :count).by(1)
      end

      it 'renders a JSON response with the new menu' do
        post api_v1_menus_url,
             params: { menu: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Menu' do
        expect do
          post api_v1_menus_url,
               params: { menu: invalid_attributes }, as: :json
        end.to change(Menu, :count).by(0)
      end

      it 'renders a JSON response with errors for the new menu' do
        post api_v1_menus_url,
             params: { menu: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) { attributes_for(:update_menu) }

      it 'updates the requested menu' do
        menu = Menu.create! valid_attributes
        patch api_v1_menu_url(menu),
              params: { menu: new_attributes }, headers: valid_headers, as: :json
        menu.reload
        expect(menu.name).to eq new_attributes[:name]
        expect(menu.code).to eq new_attributes[:code]
        expect(menu.time).to eq Menu.order(:updated_at).last.time
      end

      it 'renders a JSON response with the menu' do
        menu = Menu.create! valid_attributes
        patch api_v1_menu_url(menu),
              params: { menu: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the menu' do
        menu = Menu.create! valid_attributes
        patch api_v1_menu_url(menu),
              params: { menu: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested menu' do
      menu = Menu.create! valid_attributes
      expect do
        delete api_v1_menu_url(menu), headers: valid_headers, as: :json
      end.to change(Menu, :count).by(-1)
    end
  end
end
